kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=worker_1"
    extraMounts:
      - hostPath: /Users/tin/fun/k8s-airflow-orchestration/k8s/data
        containerPath: /tmp/data
      - hostPath: /Users/tin/fun/k8s-airflow-orchestration/dags
        containerPath: /tmp/dags
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=worker_2"
    extraMounts:
      - hostPath: /Users/tin/fun/k8s-airflow-orchestration/k8s/data
        containerPath: /tmp/data
      - hostPath: /Users/tin/fun/k8s-airflow-orchestration/dags
        containerPath: /tmp/dags
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=worker_3"
    extraMounts:
      - hostPath: /Users/tin/fun/k8s-airflow-orchestration/k8s/data
        containerPath: /tmp/data
      - hostPath: /Users/tin/fun/k8s-airflow-orchestration/dags
        containerPath: /tmp/dags
